matrix:
  include:
    - language: cpp
      addons:
        apt:
          packages:
            - libxerces-c-dev
            
      script:
        - mkdir regxmllib/build
        - cd regxmllib/build
        - cmake ..
        - cmake --build .
        - ctest .
      
    - language: java
      install:
        - sudo apt-get install ant-optional
      script:
        - cd regxmllib
        - ant test